/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaappveiculos;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author junio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    // INSTANCIANDO A CLASSE VEÍCULO DE FORMA GLOBAL À CLASSE TelaPrincipal
    Veiculo veiculo = new Veiculo();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoTipoVeiculo = new javax.swing.ButtonGroup();
        GrupoTipoCombustivel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro de Veículos e Cálculo de IPVA");

        jLabel1.setText("Tipo do Veículo:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Ano de Fabricação:");

        jLabel5.setText("Tipo de Combustível:");

        jLabel6.setText("Placa:");

        jLabel7.setText("Valor:");

        jLabel8.setText("Status:");

        GrupoTipoVeiculo.add(jRadioButton1);
        jRadioButton1.setText("Carro");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        GrupoTipoVeiculo.add(jRadioButton2);
        jRadioButton2.setText("Motocicleta");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        GrupoTipoCombustivel.add(jRadioButton3);
        jRadioButton3.setText("Flex");

        GrupoTipoCombustivel.add(jRadioButton4);
        jRadioButton4.setText("Gasolina");

        GrupoTipoCombustivel.add(jRadioButton5);
        jRadioButton5.setText("Gás");

        GrupoTipoCombustivel.add(jRadioButton6);
        jRadioButton6.setText("Elétrico");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calcular IPVA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sair");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(jTextField2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // MÉTODO PARA O BOTÃO CADASTRAR AO EVENTO DE CLIQUE
        // TIPO DE VEÍCULO
        if (jRadioButton1.isSelected()){ // Opção Carro para Tipo de Veiculo
            veiculo.setTipo_veiculo("Carro");
        }
        else if (jRadioButton2.isSelected()){ // Opção Motocicleta para Tipo de Veiculo
            veiculo.setTipo_veiculo("Motocicleta");
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de veículo válido!", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // MARCA
        // OBS: como a verificação de igualdade " == " não funcionou, tivemos que usar um método próprio do Java .equals()
        if(jTextField1.getText().equals("") || jTextField1.getText().equals(" ")){ // Verificando se o campo de texto para a marca está vazio
            JOptionPane.showMessageDialog(null, "Informe a marca do veículo", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            veiculo.setMarca(jTextField1.getText());
        }
        
        // MODELO
        if(jTextField2.getText().equals("") || jTextField2.getText().equals(" ")){ // Verificando se o campo de texto para o modelo está vazio
            JOptionPane.showMessageDialog(null, "Informe um modelo do veículo", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            veiculo.setModelo(jTextField2.getText());
        }
        
        // ANO DE FABRICAÇÃO
        if (jTextField3.getText().equals("") || jTextField3.getText().equals(" ")){ // Verificando se o campo de texto para o ano do veículo está vazio
            JOptionPane.showMessageDialog(null, "Informe um ano válido", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            veiculo.setAno_fab(Integer.parseInt(jTextField3.getText()));
        }
        
        // TIPO DE COMBUSTÍVEL
        if (jRadioButton3.isSelected()){
            veiculo.setCombustivel("Flex");
        }
        else if (jRadioButton4.isSelected()){
            veiculo.setCombustivel("Gasolina");
        }
        else if (jRadioButton5.isSelected()){
            veiculo.setCombustivel("Gás");
        }
        else if (jRadioButton6.isSelected()){
            veiculo.setCombustivel("Elétrico");
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um tipo de combustível válido!", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        
        // PLACA
        if (jTextField4.getText().equals("") || jTextField4.getText().equals(" ")){ // Verificando se o campo de texto para a placa está vazio
            JOptionPane.showMessageDialog(null, "Informe uma placa", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            veiculo.setPlaca(jTextField4.getText());
        }
        
        // VALOR DO VEÍCULO
        if (jTextField5.getText().equals("") || jTextField5.getText().equals(" ")){ // Verificando se o campo de texto para o valor está vazio
            JOptionPane.showMessageDialog(null, "Informe o valor do veículo", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (Double.parseDouble(jTextField5.getText()) <= 0){ // Verificando se o valor inserido foi menor ou igual a 0
            JOptionPane.showMessageDialog(null, "O valor do veículo precisa ser maior que R$0,00", "Erro", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            veiculo.setValor(Double.parseDouble(jTextField5.getText()));
        }
        
        jLabel8.setText("Status: Veículo cadastrado com sucesso!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // MÉTODO PARA O BOTÃO CALCULAR IPVA AO EVENTO DE CLIQUE
        String mensagem = "";
        double ipva;
        
        if (veiculo.getMarca() == null || veiculo.getModelo() == null || veiculo.getTipo_veiculo() == null || veiculo.getCombustivel() == null || veiculo.getPlaca() == null){ // Verificando se o veículo foi cadastrado
            JOptionPane.showMessageDialog(null, "Nenhum veículo foi cadastrado", "ERRO", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (veiculo.getAno_fab() <= 2005){ // Verificando o ano para calcular o IPVA
            mensagem = "\n Tipo do Veículo.......: " + veiculo.getTipo_veiculo() +
                       "\n Marca.................: " + veiculo.getMarca() +
                       "\n Modelo................: " + veiculo.getModelo() +
                       "\n Ano de Fabricação.....: " + veiculo.getAno_fab() +
                       "\n Tipo de Combustível...: " + veiculo.getCombustivel() +
                       "\n Placa.................: " + veiculo.getPlaca() +
                       "\n Valor.................: R$" + veiculo.getValor() +
                       "\n Valor do IPVA.........: VEÍCULO ISENTO DE IPVA!";
            
            JOptionPane.showMessageDialog(null, mensagem, "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            ipva = 0;
            if (veiculo.getTipo_veiculo() == "Carro"){ // Verificando se o tipo de veículo é um carro
                if (veiculo.getCombustivel() == "Flex" || veiculo.getCombustivel() == "Gasolina") { // Verificando se o tipo de combustivel do carro é Flex ou gasolina
                    ipva = veiculo.getValor() * 0.04;
                }
                else if (veiculo.getCombustivel() == "Gás" || veiculo.getCombustivel() == "Elétrico") { // Verificando se o tipo de combustivel do carro é Gás
                    ipva = veiculo.getValor() * 0.03;
                }
            }
            else{
                ipva = veiculo.getValor() * 0.02;
            }
            
            mensagem = "\n Tipo do Veículo.......: " + veiculo.getTipo_veiculo() +
                       "\n Marca.................: " + veiculo.getMarca() +
                       "\n Modelo................: " + veiculo.getModelo() +
                       "\n Ano de Fabricação.....: " + veiculo.getAno_fab() +
                       "\n Tipo de Combustível...: " + veiculo.getCombustivel() +
                       "\n Placa.................: " + veiculo.getPlaca() +
                       "\n Valor.................: R$" + veiculo.getValor() +
                       "\n Valor do IPVA.........: R$" + ipva;
            
            JOptionPane.showMessageDialog(null, mensagem, "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // MÉTODO PARA O BOTÃO NOVO AO EVENTO DE CLIQUE
        // LIMPANDO O FORMULÁRIO
        GrupoTipoVeiculo.clearSelection();
        GrupoTipoCombustivel.clearSelection();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jLabel8.setText("Status:");
        
        // LIMPANDO OS ATRIBUTOS DO OBJETO
        veiculo.setTipo_veiculo(null);
        veiculo.setMarca(null);
        veiculo.setModelo(null);
        veiculo.setAno_fab(0);
        veiculo.setCombustivel(null);
        veiculo.setPlaca(null);
        veiculo.setValor(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // MÉTODO PARA O BOTÃO SAIR AO EVENTO DE CLIQUE
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoTipoCombustivel;
    private javax.swing.ButtonGroup GrupoTipoVeiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
